Created log @ 2023-10-27 21:19:29.512133
################
In Pycraft. Error: None @ 2023-10-27 21:19:29.512133
Traceback (most recent call last):
  File "D:\Documents\GitHub\PycraftReimagined\src\programs\game_engine.py", line 168, in __init__
    self.clouds_prog["render_fog"] = Registry.render_fog
  File "C:\Users\pamj0\AppData\Local\Programs\Python\Python310\lib\site-packages\moderngl\__init__.py", line 501, in __setitem__
    self._members[key].value = value
KeyError: 'render_fog'
################
################
In Pycraft. Error: None @ 2023-10-27 21:21:33.708794
Traceback (most recent call last):
  File "D:\Documents\GitHub\PycraftReimagined\src\programs\game_engine.py", line 105, in __init__
    self.clouds_prog) = shader_utils.load_programs().load_program_files()
  File "D:\Documents\GitHub\PycraftReimagined\src\programs\utility\shader_utils.py", line 45, in load_program_files
    clouds_prog = moderngl_window.WindowConfig.load_program(
  File "C:\Users\pamj0\AppData\Local\Programs\Python\Python310\lib\site-packages\moderngl_window\context\base\window.py", line 1381, in load_program
    return resources.programs.load(
  File "C:\Users\pamj0\AppData\Local\Programs\Python\Python310\lib\site-packages\moderngl_window\resources\programs.py", line 33, in load
    return super().load(meta)
  File "C:\Users\pamj0\AppData\Local\Programs\Python\Python310\lib\site-packages\moderngl_window\resources\base.py", line 52, in load
    return meta.loader_cls(meta).load()
  File "C:\Users\pamj0\AppData\Local\Programs\Python\Python310\lib\site-packages\moderngl_window\loaders\program\single.py", line 59, in load
    prog = shaders.create()
  File "C:\Users\pamj0\AppData\Local\Programs\Python\Python310\lib\site-packages\moderngl_window\opengl\program.py", line 169, in create
    program = self.ctx.program(
  File "C:\Users\pamj0\AppData\Local\Programs\Python\Python310\lib\site-packages\moderngl\__init__.py", line 2092, in program
    res.mglo, res._members, res._subroutines, res._geom, res._glo = self.mglo.program(
_moderngl.Error: GLSL Compiler failed

vertex_shader
=============
0(20) : error C1067: too little data in type constructor


################
################
In Pycraft. Error: None @ 2023-10-27 21:32:6.369772
Traceback (most recent call last):
  File "D:\Documents\GitHub\PycraftReimagined\src\programs\game_engine.py", line 107, in __init__
    self.clouds_prog) = shader_utils.load_programs().load_program_files()
  File "D:\Documents\GitHub\PycraftReimagined\src\programs\utility\shader_utils.py", line 45, in load_program_files
    clouds_prog = moderngl_window.WindowConfig.load_program(
  File "C:\Users\pamj0\AppData\Local\Programs\Python\Python310\lib\site-packages\moderngl_window\context\base\window.py", line 1381, in load_program
    return resources.programs.load(
  File "C:\Users\pamj0\AppData\Local\Programs\Python\Python310\lib\site-packages\moderngl_window\resources\programs.py", line 33, in load
    return super().load(meta)
  File "C:\Users\pamj0\AppData\Local\Programs\Python\Python310\lib\site-packages\moderngl_window\resources\base.py", line 52, in load
    return meta.loader_cls(meta).load()
  File "C:\Users\pamj0\AppData\Local\Programs\Python\Python310\lib\site-packages\moderngl_window\loaders\program\single.py", line 59, in load
    prog = shaders.create()
  File "C:\Users\pamj0\AppData\Local\Programs\Python\Python310\lib\site-packages\moderngl_window\opengl\program.py", line 169, in create
    program = self.ctx.program(
  File "C:\Users\pamj0\AppData\Local\Programs\Python\Python310\lib\site-packages\moderngl\__init__.py", line 2092, in program
    res.mglo, res._members, res._subroutines, res._geom, res._glo = self.mglo.program(
_moderngl.Error: GLSL Compiler failed

vertex_shader
=============
0(61) : error C7608: OpenGL does not allow using 'discard or demote' in this profile
0(64) : error C1503: undefined variable "render_fog"
0(76) : error C0000: syntax error, unexpected identifier, expecting ',' or ';' at token "gl_Position"


################
################
In Pycraft. Error: None @ 2023-10-27 21:32:35.118058
Traceback (most recent call last):
  File "D:\Documents\GitHub\PycraftReimagined\src\programs\game_engine.py", line 107, in __init__
    self.clouds_prog) = shader_utils.load_programs().load_program_files()
  File "D:\Documents\GitHub\PycraftReimagined\src\programs\utility\shader_utils.py", line 45, in load_program_files
    clouds_prog = moderngl_window.WindowConfig.load_program(
  File "C:\Users\pamj0\AppData\Local\Programs\Python\Python310\lib\site-packages\moderngl_window\context\base\window.py", line 1381, in load_program
    return resources.programs.load(
  File "C:\Users\pamj0\AppData\Local\Programs\Python\Python310\lib\site-packages\moderngl_window\resources\programs.py", line 33, in load
    return super().load(meta)
  File "C:\Users\pamj0\AppData\Local\Programs\Python\Python310\lib\site-packages\moderngl_window\resources\base.py", line 52, in load
    return meta.loader_cls(meta).load()
  File "C:\Users\pamj0\AppData\Local\Programs\Python\Python310\lib\site-packages\moderngl_window\loaders\program\single.py", line 59, in load
    prog = shaders.create()
  File "C:\Users\pamj0\AppData\Local\Programs\Python\Python310\lib\site-packages\moderngl_window\opengl\program.py", line 169, in create
    program = self.ctx.program(
  File "C:\Users\pamj0\AppData\Local\Programs\Python\Python310\lib\site-packages\moderngl\__init__.py", line 2092, in program
    res.mglo, res._members, res._subroutines, res._geom, res._glo = self.mglo.program(
_moderngl.Error: GLSL Compiler failed

vertex_shader
=============
0(64) : error C0000: syntax error, unexpected identifier, expecting ',' or ';' at token "gl_Position"


################
################
In Pycraft. Error: None @ 2023-10-27 21:45:25.779656
Traceback (most recent call last):
  File "D:\Documents\GitHub\PycraftReimagined\src\programs\game_engine.py", line 408, in render_game_engine
    self.clouds_prog["cloud_scale"] = cloud_scale
  File "C:\Users\pamj0\AppData\Local\Programs\Python\Python310\lib\site-packages\moderngl\__init__.py", line 501, in __setitem__
    self._members[key].value = value
KeyError: 'cloud_scale'
################
################
In Pycraft. Error: None @ 2023-10-27 21:53:22.625565
Traceback (most recent call last):
  File "D:\Documents\GitHub\PycraftReimagined\src\programs\game_engine.py", line 107, in __init__
    self.objects_shadow["map"] = self.vao.instance(self.depth_prog)
AttributeError: 'create_game_engine' object has no attribute 'objects_shadow'
################
################
In Pycraft. Error: None @ 2023-10-29 10:23:34.54014
Traceback (most recent call last):
  File "D:\Documents\GitHub\PycraftReimagined\src\programs\game_engine.py", line 103, in __init__
    self.clouds_prog) = shader_utils.load_programs().load_program_files()
  File "D:\Documents\GitHub\PycraftReimagined\src\programs\utility\shader_utils.py", line 40, in load_program_files
    skysphere_prog = moderngl_window.WindowConfig.load_program(
  File "C:\Users\pamj0\AppData\Local\Programs\Python\Python310\lib\site-packages\moderngl_window\context\base\window.py", line 1381, in load_program
    return resources.programs.load(
  File "C:\Users\pamj0\AppData\Local\Programs\Python\Python310\lib\site-packages\moderngl_window\resources\programs.py", line 33, in load
    return super().load(meta)
  File "C:\Users\pamj0\AppData\Local\Programs\Python\Python310\lib\site-packages\moderngl_window\resources\base.py", line 52, in load
    return meta.loader_cls(meta).load()
  File "C:\Users\pamj0\AppData\Local\Programs\Python\Python310\lib\site-packages\moderngl_window\loaders\program\single.py", line 59, in load
    prog = shaders.create()
  File "C:\Users\pamj0\AppData\Local\Programs\Python\Python310\lib\site-packages\moderngl_window\opengl\program.py", line 169, in create
    program = self.ctx.program(
  File "C:\Users\pamj0\AppData\Local\Programs\Python\Python310\lib\site-packages\moderngl\__init__.py", line 2092, in program
    res.mglo, res._members, res._subroutines, res._geom, res._glo = self.mglo.program(
_moderngl.Error: GLSL Compiler failed

fragment_shader
===============
0(101) : error C1503: undefined variable "uv0"
0(108) : error C0000: syntax error, unexpected identifier, expecting ',' or ';' at token "fragColor"


################
################
In Pycraft. Error: None @ 2023-10-29 10:23:50.895895
Traceback (most recent call last):
  File "D:\Documents\GitHub\PycraftReimagined\src\programs\game_engine.py", line 103, in __init__
    self.clouds_prog) = shader_utils.load_programs().load_program_files()
  File "D:\Documents\GitHub\PycraftReimagined\src\programs\utility\shader_utils.py", line 40, in load_program_files
    skysphere_prog = moderngl_window.WindowConfig.load_program(
  File "C:\Users\pamj0\AppData\Local\Programs\Python\Python310\lib\site-packages\moderngl_window\context\base\window.py", line 1381, in load_program
    return resources.programs.load(
  File "C:\Users\pamj0\AppData\Local\Programs\Python\Python310\lib\site-packages\moderngl_window\resources\programs.py", line 33, in load
    return super().load(meta)
  File "C:\Users\pamj0\AppData\Local\Programs\Python\Python310\lib\site-packages\moderngl_window\resources\base.py", line 52, in load
    return meta.loader_cls(meta).load()
  File "C:\Users\pamj0\AppData\Local\Programs\Python\Python310\lib\site-packages\moderngl_window\loaders\program\single.py", line 59, in load
    prog = shaders.create()
  File "C:\Users\pamj0\AppData\Local\Programs\Python\Python310\lib\site-packages\moderngl_window\opengl\program.py", line 169, in create
    program = self.ctx.program(
  File "C:\Users\pamj0\AppData\Local\Programs\Python\Python310\lib\site-packages\moderngl\__init__.py", line 2092, in program
    res.mglo, res._members, res._subroutines, res._geom, res._glo = self.mglo.program(
_moderngl.Error: GLSL Compiler failed

fragment_shader
===============
0(101) : error C1503: undefined variable "uv0"
0(108) : error C0000: syntax error, unexpected identifier, expecting ',' or ';' at token "fragColor"


################
################
In Pycraft. Error: None @ 2023-10-29 10:24:16.408923
Traceback (most recent call last):
  File "D:\Documents\GitHub\PycraftReimagined\src\programs\game_engine.py", line 103, in __init__
    self.clouds_prog) = shader_utils.load_programs().load_program_files()
  File "D:\Documents\GitHub\PycraftReimagined\src\programs\utility\shader_utils.py", line 40, in load_program_files
    skysphere_prog = moderngl_window.WindowConfig.load_program(
  File "C:\Users\pamj0\AppData\Local\Programs\Python\Python310\lib\site-packages\moderngl_window\context\base\window.py", line 1381, in load_program
    return resources.programs.load(
  File "C:\Users\pamj0\AppData\Local\Programs\Python\Python310\lib\site-packages\moderngl_window\resources\programs.py", line 33, in load
    return super().load(meta)
  File "C:\Users\pamj0\AppData\Local\Programs\Python\Python310\lib\site-packages\moderngl_window\resources\base.py", line 52, in load
    return meta.loader_cls(meta).load()
  File "C:\Users\pamj0\AppData\Local\Programs\Python\Python310\lib\site-packages\moderngl_window\loaders\program\single.py", line 59, in load
    prog = shaders.create()
  File "C:\Users\pamj0\AppData\Local\Programs\Python\Python310\lib\site-packages\moderngl_window\opengl\program.py", line 169, in create
    program = self.ctx.program(
  File "C:\Users\pamj0\AppData\Local\Programs\Python\Python310\lib\site-packages\moderngl\__init__.py", line 2092, in program
    res.mglo, res._members, res._subroutines, res._geom, res._glo = self.mglo.program(
_moderngl.Error: GLSL Compiler failed

fragment_shader
===============
0(108) : error C0000: syntax error, unexpected identifier, expecting ',' or ';' at token "fragColor"


################
################
In Pycraft. Error: None @ 2023-10-29 10:24:46.875336
Traceback (most recent call last):
  File "D:\Documents\GitHub\PycraftReimagined\src\programs\game_engine.py", line 103, in __init__
    self.clouds_prog) = shader_utils.load_programs().load_program_files()
  File "D:\Documents\GitHub\PycraftReimagined\src\programs\utility\shader_utils.py", line 40, in load_program_files
    skysphere_prog = moderngl_window.WindowConfig.load_program(
  File "C:\Users\pamj0\AppData\Local\Programs\Python\Python310\lib\site-packages\moderngl_window\context\base\window.py", line 1381, in load_program
    return resources.programs.load(
  File "C:\Users\pamj0\AppData\Local\Programs\Python\Python310\lib\site-packages\moderngl_window\resources\programs.py", line 33, in load
    return super().load(meta)
  File "C:\Users\pamj0\AppData\Local\Programs\Python\Python310\lib\site-packages\moderngl_window\resources\base.py", line 52, in load
    return meta.loader_cls(meta).load()
  File "C:\Users\pamj0\AppData\Local\Programs\Python\Python310\lib\site-packages\moderngl_window\loaders\program\single.py", line 59, in load
    prog = shaders.create()
  File "C:\Users\pamj0\AppData\Local\Programs\Python\Python310\lib\site-packages\moderngl_window\opengl\program.py", line 169, in create
    program = self.ctx.program(
  File "C:\Users\pamj0\AppData\Local\Programs\Python\Python310\lib\site-packages\moderngl\__init__.py", line 2092, in program
    res.mglo, res._members, res._subroutines, res._geom, res._glo = self.mglo.program(
_moderngl.Error: GLSL Compiler failed

fragment_shader
===============
0(108) : error C1503: undefined variable "cloud_col"


################
################
In Pycraft. Error: None @ 2023-10-29 10:25:9.755686
Traceback (most recent call last):
  File "D:\Documents\GitHub\PycraftReimagined\src\programs\game_engine.py", line 103, in __init__
    self.clouds_prog) = shader_utils.load_programs().load_program_files()
  File "D:\Documents\GitHub\PycraftReimagined\src\programs\utility\shader_utils.py", line 40, in load_program_files
    skysphere_prog = moderngl_window.WindowConfig.load_program(
  File "C:\Users\pamj0\AppData\Local\Programs\Python\Python310\lib\site-packages\moderngl_window\context\base\window.py", line 1381, in load_program
    return resources.programs.load(
  File "C:\Users\pamj0\AppData\Local\Programs\Python\Python310\lib\site-packages\moderngl_window\resources\programs.py", line 33, in load
    return super().load(meta)
  File "C:\Users\pamj0\AppData\Local\Programs\Python\Python310\lib\site-packages\moderngl_window\resources\base.py", line 52, in load
    return meta.loader_cls(meta).load()
  File "C:\Users\pamj0\AppData\Local\Programs\Python\Python310\lib\site-packages\moderngl_window\loaders\program\single.py", line 59, in load
    prog = shaders.create()
  File "C:\Users\pamj0\AppData\Local\Programs\Python\Python310\lib\site-packages\moderngl_window\opengl\program.py", line 169, in create
    program = self.ctx.program(
  File "C:\Users\pamj0\AppData\Local\Programs\Python\Python310\lib\site-packages\moderngl\__init__.py", line 2092, in program
    res.mglo, res._members, res._subroutines, res._geom, res._glo = self.mglo.program(
_moderngl.Error: GLSL Compiler failed

fragment_shader
===============
0(107) : error C1503: undefined variable "cloud_col"


################
################
In Pycraft. Error: None @ 2023-10-29 10:25:26.740137
Traceback (most recent call last):
  File "D:\Documents\GitHub\PycraftReimagined\src\programs\game_engine.py", line 103, in __init__
    self.clouds_prog) = shader_utils.load_programs().load_program_files()
  File "D:\Documents\GitHub\PycraftReimagined\src\programs\utility\shader_utils.py", line 40, in load_program_files
    skysphere_prog = moderngl_window.WindowConfig.load_program(
  File "C:\Users\pamj0\AppData\Local\Programs\Python\Python310\lib\site-packages\moderngl_window\context\base\window.py", line 1381, in load_program
    return resources.programs.load(
  File "C:\Users\pamj0\AppData\Local\Programs\Python\Python310\lib\site-packages\moderngl_window\resources\programs.py", line 33, in load
    return super().load(meta)
  File "C:\Users\pamj0\AppData\Local\Programs\Python\Python310\lib\site-packages\moderngl_window\resources\base.py", line 52, in load
    return meta.loader_cls(meta).load()
  File "C:\Users\pamj0\AppData\Local\Programs\Python\Python310\lib\site-packages\moderngl_window\loaders\program\single.py", line 59, in load
    prog = shaders.create()
  File "C:\Users\pamj0\AppData\Local\Programs\Python\Python310\lib\site-packages\moderngl_window\opengl\program.py", line 169, in create
    program = self.ctx.program(
  File "C:\Users\pamj0\AppData\Local\Programs\Python\Python310\lib\site-packages\moderngl\__init__.py", line 2092, in program
    res.mglo, res._members, res._subroutines, res._geom, res._glo = self.mglo.program(
_moderngl.Error: GLSL Compiler failed

fragment_shader
===============
(0) : error C0000: syntax error, unexpected $end at token "<EOF>"


################
################
In Pycraft. Error: None @ 2023-10-29 10:25:43.530686
Traceback (most recent call last):
  File "D:\Documents\GitHub\PycraftReimagined\src\programs\game_engine.py", line 103, in __init__
    self.clouds_prog) = shader_utils.load_programs().load_program_files()
  File "D:\Documents\GitHub\PycraftReimagined\src\programs\utility\shader_utils.py", line 45, in load_program_files
    clouds_prog = moderngl_window.WindowConfig.load_program(
  File "C:\Users\pamj0\AppData\Local\Programs\Python\Python310\lib\site-packages\moderngl_window\context\base\window.py", line 1381, in load_program
    return resources.programs.load(
  File "C:\Users\pamj0\AppData\Local\Programs\Python\Python310\lib\site-packages\moderngl_window\resources\programs.py", line 33, in load
    return super().load(meta)
  File "C:\Users\pamj0\AppData\Local\Programs\Python\Python310\lib\site-packages\moderngl_window\resources\base.py", line 52, in load
    return meta.loader_cls(meta).load()
  File "C:\Users\pamj0\AppData\Local\Programs\Python\Python310\lib\site-packages\moderngl_window\loaders\program\single.py", line 59, in load
    prog = shaders.create()
  File "C:\Users\pamj0\AppData\Local\Programs\Python\Python310\lib\site-packages\moderngl_window\opengl\program.py", line 169, in create
    program = self.ctx.program(
  File "C:\Users\pamj0\AppData\Local\Programs\Python\Python310\lib\site-packages\moderngl\__init__.py", line 2092, in program
    res.mglo, res._members, res._subroutines, res._geom, res._glo = self.mglo.program(
_moderngl.Error: GLSL Compiler failed

fragment_shader
===============
0(96) : error C1503: undefined variable "uv"


################
################
In Pycraft. Error: None @ 2023-10-29 10:26:49.408956
Traceback (most recent call last):
  File "D:\Documents\GitHub\PycraftReimagined\src\programs\game_engine.py", line 103, in __init__
    self.clouds_prog) = shader_utils.load_programs().load_program_files()
  File "D:\Documents\GitHub\PycraftReimagined\src\programs\utility\shader_utils.py", line 45, in load_program_files
    clouds_prog = moderngl_window.WindowConfig.load_program(
  File "C:\Users\pamj0\AppData\Local\Programs\Python\Python310\lib\site-packages\moderngl_window\context\base\window.py", line 1381, in load_program
    return resources.programs.load(
  File "C:\Users\pamj0\AppData\Local\Programs\Python\Python310\lib\site-packages\moderngl_window\resources\programs.py", line 33, in load
    return super().load(meta)
  File "C:\Users\pamj0\AppData\Local\Programs\Python\Python310\lib\site-packages\moderngl_window\resources\base.py", line 52, in load
    return meta.loader_cls(meta).load()
  File "C:\Users\pamj0\AppData\Local\Programs\Python\Python310\lib\site-packages\moderngl_window\loaders\program\single.py", line 59, in load
    prog = shaders.create()
  File "C:\Users\pamj0\AppData\Local\Programs\Python\Python310\lib\site-packages\moderngl_window\opengl\program.py", line 169, in create
    program = self.ctx.program(
  File "C:\Users\pamj0\AppData\Local\Programs\Python\Python310\lib\site-packages\moderngl\__init__.py", line 2092, in program
    res.mglo, res._members, res._subroutines, res._geom, res._glo = self.mglo.program(
_moderngl.Error: GLSL Compiler failed

fragment_shader
===============
0(96) : error C1503: undefined variable "uv"


################
################
In Pycraft. Error: None @ 2023-10-29 10:28:10.867672
Traceback (most recent call last):
  File "D:\Documents\GitHub\PycraftReimagined\src\programs\game_engine.py", line 164, in __init__
    self.sky_sphere_prog["render_fog"] = Registry.render_fog
  File "C:\Users\pamj0\AppData\Local\Programs\Python\Python310\lib\site-packages\moderngl\__init__.py", line 501, in __setitem__
    self._members[key].value = value
KeyError: 'render_fog'
################
################
In Pycraft. Error: None @ 2023-10-29 10:28:52.443923
Traceback (most recent call last):
  File "D:\Documents\GitHub\PycraftReimagined\src\programs\game_engine.py", line 164, in __init__
    self.sky_sphere_prog["render_fog"] = Registry.render_fog
  File "C:\Users\pamj0\AppData\Local\Programs\Python\Python310\lib\site-packages\moderngl\__init__.py", line 501, in __setitem__
    self._members[key].value = value
KeyError: 'render_fog'
################
################
In Pycraft. Error: None @ 2023-10-29 10:29:17.790576
Traceback (most recent call last):
  File "D:\Documents\GitHub\PycraftReimagined\src\programs\game_engine.py", line 203, in __init__
    self.clouds_prog["w_max"].value = Registry.render_distance
AttributeError: 'create_game_engine' object has no attribute 'clouds_prog'
################
################
In Pycraft. Error: None @ 2023-10-29 10:33:50.2132
Traceback (most recent call last):
  File "D:\Documents\GitHub\PycraftReimagined\src\programs\game_engine.py", line 102, in __init__
    self.sky_sphere_prog) = shader_utils.load_programs().load_program_files()
  File "D:\Documents\GitHub\PycraftReimagined\src\programs\utility\shader_utils.py", line 40, in load_program_files
    skysphere_prog = moderngl_window.WindowConfig.load_program(
  File "C:\Users\pamj0\AppData\Local\Programs\Python\Python310\lib\site-packages\moderngl_window\context\base\window.py", line 1381, in load_program
    return resources.programs.load(
  File "C:\Users\pamj0\AppData\Local\Programs\Python\Python310\lib\site-packages\moderngl_window\resources\programs.py", line 33, in load
    return super().load(meta)
  File "C:\Users\pamj0\AppData\Local\Programs\Python\Python310\lib\site-packages\moderngl_window\resources\base.py", line 52, in load
    return meta.loader_cls(meta).load()
  File "C:\Users\pamj0\AppData\Local\Programs\Python\Python310\lib\site-packages\moderngl_window\loaders\program\single.py", line 59, in load
    prog = shaders.create()
  File "C:\Users\pamj0\AppData\Local\Programs\Python\Python310\lib\site-packages\moderngl_window\opengl\program.py", line 169, in create
    program = self.ctx.program(
  File "C:\Users\pamj0\AppData\Local\Programs\Python\Python310\lib\site-packages\moderngl\__init__.py", line 2092, in program
    res.mglo, res._members, res._subroutines, res._geom, res._glo = self.mglo.program(
_moderngl.Error: GLSL Compiler failed

fragment_shader
===============
0(97) : error C1105: cannot call a non-function


################
################
In Pycraft. Error: None @ 2023-10-29 10:36:18.693716
Traceback (most recent call last):
  File "D:\Documents\GitHub\PycraftReimagined\src\programs\game_engine.py", line 107, in __init__
    self.sky_sphere_prog["texture0"].value = 0
  File "C:\Users\pamj0\AppData\Local\Programs\Python\Python310\lib\site-packages\moderngl\__init__.py", line 498, in __getitem__
    return self._members[key]
KeyError: 'texture0'
################
################
In Pycraft. Error: None @ 2023-10-29 10:37:1.926024
Traceback (most recent call last):
  File "D:\Documents\GitHub\PycraftReimagined\src\programs\game_engine.py", line 107, in __init__
    self.sky_sphere_prog["texture0"].value = 0
  File "C:\Users\pamj0\AppData\Local\Programs\Python\Python310\lib\site-packages\moderngl\__init__.py", line 498, in __getitem__
    return self._members[key]
KeyError: 'texture0'
################
################
In Pycraft. Error: None @ 2023-10-29 10:38:41.81519
Traceback (most recent call last):
  File "D:\Documents\GitHub\PycraftReimagined\src\programs\game_engine.py", line 102, in __init__
    self.sky_sphere_prog) = shader_utils.load_programs().load_program_files()
  File "D:\Documents\GitHub\PycraftReimagined\src\programs\utility\shader_utils.py", line 40, in load_program_files
    skysphere_prog = moderngl_window.WindowConfig.load_program(
  File "C:\Users\pamj0\AppData\Local\Programs\Python\Python310\lib\site-packages\moderngl_window\context\base\window.py", line 1381, in load_program
    return resources.programs.load(
  File "C:\Users\pamj0\AppData\Local\Programs\Python\Python310\lib\site-packages\moderngl_window\resources\programs.py", line 33, in load
    return super().load(meta)
  File "C:\Users\pamj0\AppData\Local\Programs\Python\Python310\lib\site-packages\moderngl_window\resources\base.py", line 52, in load
    return meta.loader_cls(meta).load()
  File "C:\Users\pamj0\AppData\Local\Programs\Python\Python310\lib\site-packages\moderngl_window\loaders\program\single.py", line 59, in load
    prog = shaders.create()
  File "C:\Users\pamj0\AppData\Local\Programs\Python\Python310\lib\site-packages\moderngl_window\opengl\program.py", line 169, in create
    program = self.ctx.program(
  File "C:\Users\pamj0\AppData\Local\Programs\Python\Python310\lib\site-packages\moderngl\__init__.py", line 2092, in program
    res.mglo, res._members, res._subroutines, res._geom, res._glo = self.mglo.program(
_moderngl.Error: GLSL Compiler failed

vertex_shader
=============
0(14) : error C0000: syntax error, unexpected ';', expecting '{' at token ";"
0(20) : error C1503: undefined variable "alpha_height"
0(21) : error C0000: syntax error, unexpected '}', expecting ',' or ';' at token "}"


################
################
In Pycraft. Error: None @ 2023-10-29 10:38:58.11734
Traceback (most recent call last):
  File "D:\Documents\GitHub\PycraftReimagined\src\programs\game_engine.py", line 102, in __init__
    self.sky_sphere_prog) = shader_utils.load_programs().load_program_files()
  File "D:\Documents\GitHub\PycraftReimagined\src\programs\utility\shader_utils.py", line 40, in load_program_files
    skysphere_prog = moderngl_window.WindowConfig.load_program(
  File "C:\Users\pamj0\AppData\Local\Programs\Python\Python310\lib\site-packages\moderngl_window\context\base\window.py", line 1381, in load_program
    return resources.programs.load(
  File "C:\Users\pamj0\AppData\Local\Programs\Python\Python310\lib\site-packages\moderngl_window\resources\programs.py", line 33, in load
    return super().load(meta)
  File "C:\Users\pamj0\AppData\Local\Programs\Python\Python310\lib\site-packages\moderngl_window\resources\base.py", line 52, in load
    return meta.loader_cls(meta).load()
  File "C:\Users\pamj0\AppData\Local\Programs\Python\Python310\lib\site-packages\moderngl_window\loaders\program\single.py", line 59, in load
    prog = shaders.create()
  File "C:\Users\pamj0\AppData\Local\Programs\Python\Python310\lib\site-packages\moderngl_window\opengl\program.py", line 169, in create
    program = self.ctx.program(
  File "C:\Users\pamj0\AppData\Local\Programs\Python\Python310\lib\site-packages\moderngl\__init__.py", line 2092, in program
    res.mglo, res._members, res._subroutines, res._geom, res._glo = self.mglo.program(
_moderngl.Error: GLSL Compiler failed

vertex_shader
=============
0(14) : error C0000: syntax error, unexpected ';', expecting '{' at token ";"
0(20) : error C1503: undefined variable "alpha_height"


################
################
In Pycraft. Error: None @ 2023-10-29 10:46:33.779645
Traceback (most recent call last):
  File "D:\Documents\GitHub\PycraftReimagined\src\programs\game_engine.py", line 244, in render_game_engine
    self.DefaultSkyCol,
AttributeError: 'create_game_engine' object has no attribute 'DefaultSkyCol'
################
################
In Pycraft. Error: None @ 2023-10-29 10:51:23.846245
Traceback (most recent call last):
  File "D:\Documents\GitHub\PycraftReimagined\src\programs\game_engine.py", line 254, in render_game_engine
    Registry.camera.rot_state(-mouse_motion)
TypeError: bad operand type for unary -: 'tuple'
################
################
In Pycraft. Error: None @ 2023-10-29 10:52:28.526491
Traceback (most recent call last):
  File "D:\Documents\GitHub\PycraftReimagined\src\programs\game_engine.py", line 254, in render_game_engine
    Registry.camera.rot_state([ -x for x in mouse_motion])
TypeError: KeyboardCamera.rot_state() missing 1 required positional argument: 'dy'
################
################
In Pycraft. Error: None @ 2023-10-29 11:24:39.579731
Traceback (most recent call last):
  File "D:\Documents\GitHub\PycraftReimagined\src\programs\pycraft_main.py", line 77, in __init__
    Registry.main_menu.main()
  File "D:\Documents\GitHub\PycraftReimagined\src\programs\main_menu.py", line 52, in main
    (_, run) = Registry.events.handle()
  File "D:\Documents\GitHub\PycraftReimagined\src\programs\utility\event_utils.py", line 79, in handle
    if event.key == Registry.input_configuration["keyboard"]["pause music"]:
KeyError: 'pause music'
################
################
In Pycraft. Error: None @ 2023-11-1 21:5:5.368575
Traceback (most recent call last):
  File "D:\Documents\GitHub\PycraftReimagined\src\programs\game_engine.py", line 131, in __init__
    self.moon_prog["color"].value = (1.0, 1.0, 1.0, 1.0)
  File "C:\Users\pamj0\AppData\Local\Programs\Python\Python310\lib\site-packages\moderngl\__init__.py", line 498, in __getitem__
    return self._members[key]
KeyError: 'color'
################
################
In Pycraft. Error: None @ 2023-11-2 15:37:35.237577
Traceback (most recent call last):
  File "D:\Documents\GitHub\PycraftReimagined\src\programs\game_engine.py", line 245, in render_game_engine
    self.cloud_offset[0] += math_utils.generate_perlin_noise(
  File "C:\Users\pamj0\AppData\Local\Programs\Python\Python310\lib\site-packages\numba\core\dispatcher.py", line 468, in _compile_for_args
    error_rewrite(e, 'typing')
  File "C:\Users\pamj0\AppData\Local\Programs\Python\Python310\lib\site-packages\numba\core\dispatcher.py", line 409, in error_rewrite
    raise e.with_traceback(None)
numba.core.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
[1mUntyped global name 'extrapolate2':[0m [1m[1mCannot determine Numba type of <class 'functools._lru_cache_wrapper'>[0m
[1m
File "src\programs\utility\math_utils.py", line 104:[0m
[1m    def generate_perlin_noise(x, y, perm):
        <source elided>
            attn1 *= attn1
[1m            value += attn1 * attn1 * extrapolate2(perm, xsb + 1, ysb + 0, dx1, dy1)
[0m            [1m^[0m[0m
[0m
################
################
In Pycraft. Error: None @ 2023-11-2 15:39:26.621628
Traceback (most recent call last):
  File "D:\Documents\GitHub\PycraftReimagined\src\programs\game_engine.py", line 282, in render_game_engine
    self.matrix, self.position = camera_utils.compute_camera.get_camera_values(
  File "D:\Documents\GitHub\PycraftReimagined\src\programs\utility\camera_utils.py", line 44, in get_camera_values
    cam_matrix = math_utils.gl_look_at(
TypeError: unhashable type: 'Vector3'
################
################
In Pycraft. Error: None @ 2023-11-2 15:40:8.544526
Traceback (most recent call last):
  File "D:\Documents\GitHub\PycraftReimagined\src\programs\game_engine.py", line 245, in render_game_engine
    self.cloud_offset[0] += math_utils.generate_perlin_noise(
TypeError: unhashable type: 'numpy.ndarray'
################
################
In Pycraft. Error: None @ 2023-11-2 15:41:1.3261
Traceback (most recent call last):
  File "D:\Documents\GitHub\PycraftReimagined\src\programs\game_engine.py", line 282, in render_game_engine
    self.matrix, self.position = camera_utils.compute_camera.get_camera_values(
  File "D:\Documents\GitHub\PycraftReimagined\src\programs\utility\camera_utils.py", line 44, in get_camera_values
    cam_matrix = math_utils.gl_look_at(
  File "D:\Documents\GitHub\PycraftReimagined\src\programs\utility\math_utils.py", line 190, in gl_look_at
    x, y, z = compute_position(
  File "C:\Users\pamj0\AppData\Local\Programs\Python\Python310\lib\site-packages\numba\core\dispatcher.py", line 468, in _compile_for_args
    error_rewrite(e, 'typing')
  File "C:\Users\pamj0\AppData\Local\Programs\Python\Python310\lib\site-packages\numba\core\dispatcher.py", line 409, in error_rewrite
    raise e.with_traceback(None)
numba.core.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
[1mUntyped global name 'lru_cache':[0m [1m[1mCannot determine Numba type of <class 'function'>[0m
[1m
File "src\programs\utility\math_utils.py", line 213:[0m
[1m    def compute_position(pos, target, up):
[1m        @lru_cache()
[0m        [1m^[0m[0m
[0m
################
################
In Pycraft. Error: None @ 2023-11-2 15:41:38.755598
Traceback (most recent call last):
  File "D:\Documents\GitHub\PycraftReimagined\src\programs\game_engine.py", line 341, in render_game_engine
    shadow_mapping_utils.shadowmapping_mathematics.compute_shadows(
  File "D:\Documents\GitHub\PycraftReimagined\src\programs\utility\shadow_mapping_utils.py", line 92, in compute_shadows
    sun_light_look_at = math_utils.look_at(
TypeError: unhashable type: 'numpy.ndarray'
################
################
In Pycraft. Error: None @ 2023-11-2 15:42:1.703040
Traceback (most recent call last):
  File "D:\Documents\GitHub\PycraftReimagined\src\programs\game_engine.py", line 341, in render_game_engine
    shadow_mapping_utils.shadowmapping_mathematics.compute_shadows(
  File "D:\Documents\GitHub\PycraftReimagined\src\programs\utility\shadow_mapping_utils.py", line 105, in compute_shadows
    mvp_light = math_utils.multiply(
TypeError: unhashable type: 'numpy.ndarray'
################
################
In Pycraft. Error: None @ 2023-11-2 15:44:37.521971
Traceback (most recent call last):
  File "D:\Documents\GitHub\PycraftReimagined\src\programs\game_engine.py", line 286, in render_game_engine
    self.matrix, self.position = camera_utils.compute_camera.get_camera_values(
TypeError: unhashable type: 'numpy.ndarray'
################